### ISSUE TITLE
Implement Chat Functionality

### ISSUE THREAD

**Issue by stephengrice** [JHU-601/flask-production#31]
(dream feature)

**Comment by KenDJohnson** [comment]
@stephengrice The client has a map of character IDs to player names right?
Could you send a chat message as the following?
```
{
  "message": "chat",
  "text": "the chat text",
}
```
for a chat to everyone, adding `"to": <id>` with the character ID for a direct message?

Then the server will send a 
```
{
  "message": "ChatMessage",
  "from": <id>,
  "private": true|false,
  "text": "the chat text"
}
```

**Comment by stephengrice** [comment]
Yep! We have that info in gameState somewhere, so should be doable.

**Comment by KenDJohnson** [comment]
Changing "from" to "from_player" because from is a python keyword and can't be used as a variable which breaks my hacky json serializing magic.
