### ISSUE TITLE
Display better info when users join

### ISSUE THREAD

**Issue by stephengrice** [JHU-601/flask-production#38]
Users that just joined do not know who is in the lobby, nor who has already registered.

**Comment by stephengrice** [comment]
Joined message now has Available (list of available characters)

Server needs to add list of registered names to that message as well (to message Joined)

**Comment by KenDJohnson** [comment]
@stephengrice how about adding:
```
"registered" : [
  { "character", CHARACTER_ID, "name": "display name" }, ...
]
```

**Comment by KenDJohnson** [comment]
@stephengrice PR for the server side impl here, can test integration on the branch in #47.

**Comment by stephengrice** [comment]
Sounds good. Thanks for adding. Going to take a look now, I'll probably go with your suggestion since it looks good
