### ISSUE TITLE
Taking Secret Passage fails

### ISSUE THREAD

**Issue by KenDJohnson** [JHU-601/flask-production#50]
Taking a secret passage does not always work on the client side, telling the user that they can't move there on their first turn, when it isn't their first turn. Maybe their location is being unset when certain invalid moves are attempted?

Repro:
* start game (with selenium script)
* move character A to a corner room
* move another character, B, to an adjacent hallway
* attempt to move character A to the hallway blocked by B, get error message
* attempt to use secret passage to move diagonally
* get "Cannot move to this location on first turn." error

@stephengrice

**Comment by KenDJohnson** [comment]
Looks like moving to other locations after certain errors also fails. Can't move to the free hallway either.

**Comment by KenDJohnson** [comment]
There may be an issue on the server side here as well.

**Comment by nguyen-jhu** [comment]
Error occurs at line 251 on state.py. 
`            self._remove_player(player, current_location)`
current_location still contains the correct location.
