### ISSUE TITLE
Disqualified handling

### ISSUE THREAD

**Issue by KenDJohnson** [JHU-601/flask-production#52]
When the `disqualified` message is received for the current player, could we have it display another message (maybe a pop-up like the errors) showing that they are disqualified, and then automatically send a `Complete` message?

The `Complete` message being sent automatically means the user doesn't have to manually go and end their turn, which is over by definition, and it'll trigger the next player and state update automatically.

**Comment by stephengrice** [comment]
Sure thing. The player who is disqualified now sees a modal (added in #51 ).

I'll add the code to auto-send Complete now.
