### ISSUE TITLE
Suspected player is not moved on Suggestion

### ISSUE THREAD

**Issue by KenDJohnson** [JHU-601/flask-production#53]
The player being called out in the `Suggestion` should be moved to the room the suggestion came from.

This is tracked on the server, but is not reflected on the client. The player is displayed in the wrong location, and when it comes to their turn they won't be able to move because the it is trying to move them from the wrong place. The client will only let them move to positions adjacent to their old location, which most of the time will be invalid moves from their real location.

The same is true of `Accusation`. The client does not update the character's position leading to the game state getting out of sync.

For the `Suggestion` and `Accusation` messages the character specified by `"suspect"` needs to be moved to `"room"`.

**Comment by stephengrice** [comment]
Thanks. This is a great writeup of the issue. Going to work this now.
