### ISSUE TITLE
Game should end if there's only 1 player left

### ISSUE THREAD

**Issue by KenDJohnson** [JHU-601/flask-production#55]
The game should end if there is only 1 player left. Upon disqualification, the server should check to see if there's only one player left, and if so end the game and send a `Winner` message (or a "you all lost" message, verify with the rules).

**Comment by stephengrice** [comment]
This reminds me of another interesting question. Does the server handle players leaving mid-game? Do we need to add a "PlayerLeft" message and update the clientside to show it, or is that overkill?

(If this is derailing, I can open a separate issue)

**Comment by KenDJohnson** [comment]
It doesn't handle that, I think we had that listed in our "Dream" goals. Basically if someone leaves the whole thing's FUBAR.
