### ISSUE TITLE
Add number of players in lobby to message Joined

### ISSUE THREAD

**Issue by stephengrice** [JHU-601/flask-production#59]
This is a nit-pick, but it may be nice to know how full the lobby is, even if players have not registered yet.

If it's difficult, no big deal, but I thought this might be quick and easy to add. 🙂

When that info is available, we can add an "X/6" indication somewhere on the waiting room screen.

@KenDJohnson

**Comment by KenDJohnson** [comment]
Yeah shouldn't be difficult. Let's see where we get this existing issues and any new ones we find tomorrow. Can add this if we're good on time there.

**Comment by KenDJohnson** [comment]
Implemented on the server in #67
