### ISSUE TITLE
Reflected XSS in all the places

### ISSUE THREAD

**Issue by KenDJohnson** [JHU-601/flask-production#64]
Haven't actually verified this, but I'm sure there is because I haven't added any input sanitization yet. I'll push some code up for that in a sec.

**Comment by KenDJohnson** [comment]
<img width="1568" alt="Screen Shot 2020-12-11 at 9 23 20 PM" src="https://user-images.githubusercontent.com/5758378/101971491-483f4900-3bf7-11eb-9bf1-5d3754df3c7a.png">
heh, confirmed.

**Comment by stephengrice** [comment]
Ooh! Interesting catch!!
We'll have to mention this fix in our presentation - I'm sure we'll get a gold star for finding a vulnerability. We can even claim we did pen testing. 😁

**Comment by KenDJohnson** [comment]
Haha yeah we may. Pretty sure we mentioned this in our requirements doc though.
